"""Phase 3 tracking fields

Revision ID: 2d8b20fd7d4d
Revises: f7f8d31aee6e
Create Date: 2026-05-30 18:53:23.817243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8b20fd7d4d'
down_revision: Union[str, None] = 'f7f8d31aee6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    
    # ### commands auto generated by Alembic - please adjust! ###
    if not inspector.has_table('resume_versions'):
        op.create_table('resume_versions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('resume_id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_resume_versions_id'), 'resume_versions', ['id'], unique=False)
        
    if not inspector.has_table('applied_suggestions'):
        op.create_table('applied_suggestions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('analysis_id', sa.Integer(), nullable=False),
        sa.Column('suggestion_type', sa.String(length=50), nullable=False),
        sa.Column('original_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_applied_suggestions_id'), 'applied_suggestions', ['id'], unique=False)
        
    analyses_columns = [col['name'] for col in inspector.get_columns('analyses')]
    if 'parent_analysis_id' not in analyses_columns:
        op.add_column('analyses', sa.Column('parent_analysis_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'analyses', 'analyses', ['parent_analysis_id'], ['id'], ondelete='SET NULL')
    
    if 'resume_version_id' not in analyses_columns:
        op.add_column('analyses', sa.Column('resume_version_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'analyses', 'resume_versions', ['resume_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_column('analyses', 'resume_version_id')
    op.drop_column('analyses', 'parent_analysis_id')
    op.drop_index(op.f('ix_applied_suggestions_id'), table_name='applied_suggestions')
    op.drop_table('applied_suggestions')
    op.drop_index(op.f('ix_resume_versions_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    # ### end Alembic commands ###
