"""Phase 1 fields

Revision ID: 435f0048d482
Revises: 001_initial
Create Date: 2026-05-30 18:30:39.121798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435f0048d482'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('readiness_label', sa.String(length=50), nullable=True))
    op.add_column('analyses', sa.Column('score_explanation', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('category_scores', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('top_fixes', sa.JSON(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('analyses', 'top_fixes')
    op.drop_column('analyses', 'category_scores')
    op.drop_column('analyses', 'score_explanation')
    op.drop_column('analyses', 'readiness_label')
    # ### end Alembic commands ###
