"""Phase 2 fields

Revision ID: f7f8d31aee6e
Revises: 435f0048d482
Create Date: 2026-05-30 18:42:46.509945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f8d31aee6e'
down_revision: Union[str, None] = '435f0048d482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('section_diagnostics', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('formatting_checks', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('bullet_analysis', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('keyword_grouping', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'keyword_grouping')
    op.drop_column('analyses', 'bullet_analysis')
    op.drop_column('analyses', 'formatting_checks')
    op.drop_column('analyses', 'section_diagnostics')
    # ### end Alembic commands ###
